spring:
  security:
    jwt:
      key: abcdefghijk
      expire: 2
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    lettuce:  # 显式配置Lettuce连接工厂
      pool:
        enabled: true
    timeout: 5000ms  # 增加超时时间
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdata?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    hikari:


mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity #需要配置成你当前包下的实体类路径
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
