spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
  web:
    resources:
      add-mappings: true

  # ————————————————————————————————————————————————————————————————
  #这是 服务器 发送邮箱 的主机，后续交付需要 管理员 自行配置。  mail
  #—————————————————————————————————————————————————————————————————
  mail:
    host: smtp.163.com
    username: zly15727831672@163.com
    password: DDWFJSdn7rPzjBME
  rabbitmq:
    addresses: localhost
    stream:
      username: guest
      password: guest
      virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 2
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123
      lettuce:  # 显式配置Lettuce连接工厂
        pool:
          enabled: true
      timeout: 5000ms  # 增加超时时间
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdatav2?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB


ipfs:
  host: /ip4/127.0.0.1/tcp/5001  # 使用完整路径格式
  # port: 5001  # 删除此行，避免冲突
  gateway: http://127.0.0.1:8082  # 使用本地网关


mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity #需要配置成你当前包下的实体类路径
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # path: 配置swagger-ui.html/UI界面的访问路径,默认为/swagger-ui.html
    tags-sorter: alpha
    # tags-sorter: 接口文档中的tags排序规则,默认为alpha,可选值为alpha(按字母顺序排序)或as-is(按照在代码中定义的顺序排序)
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    # path: 配置api-docs的访问路径,默认为/v3/api-docs
  group-configs:
    # group-configs: 配置分组信息
    - group: 'default'
      # group: 分组名称
      paths-to-match: '/**'
      # paths-to-match: 配置要匹配的路径,默认为/**
      packages-to-scan: com.example.controller
      # packages-to-scan: 配置要扫描的包的路径,直接配置为Controller类所在的包名即可

# ————————————————————————————————————————————————————————————————
#这是 alipay 沙箱环境的配置 ，后续交付需要 管理员 自行配置。  alipay
#—————————————————————————————————————————————————————————————————
alipay:
  appId: 9021000149697578

  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkMIOsWi1J6bLy0/GkTO9h8GyYeR2NayrhQgTqiF0wVGTw8EQtpMIxNuHZ9HPmnDd+dOuKj7pKKC/H4+N81JSCU6pmg0qpsKNliPoGaOCaTLnxckkofUsBZH0lYROdYZIt48xJQYJv/4lQvmtq6geT0KkqGtrCSk7H8h73DeHVQbo7ly1ndQO1uHrTYe94KyL4ro5MxipPhRdsR9dPaHnszf+r4d4hXd8qXCozheZJ2p2Fw9Tvf/Pb5vkHEu9IbeU13OTbX5pq8jD2hdRGv2NruRGWYE4CLcY3tmha76U29fpagBIOU0B14KBJr4KLLi4yUCnXcrWm/JJUk0YJURXCQIDAQAB
  # 异步通知回调地址 - 用户回调地址
  notifyUrl: http://demotestccit.natapp1.cc/alipay/notify #natapp的免费隧道会过期，需要重新获取

  app-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCz/dHf6pa+wxkySmmJf5ZwVPcWLl8B/XBUfEInwpcxhY89KU6XM8rqzjy6R4pJQA6rSsEuOdeDChG1C/J4NGF6k+A6rFekSRUUKsCfzehNJ1KaEstDTffY8dndxikkGplR0+84FBS5JKr+E9Xh65aQasimKPAa691WKJFLWXHn2u2DNc0npPsjnGCTyWOGoTrw1v7yWYitxq2/iLkPqiQIEyMX64Dfu0J4ko4xrBeuGSb7lgr0W93gcejyp9xrYkgiYmTDeyanWtYQPGZO9UgY3MYVtInbbUL+qL2dxA1kBXXvhBXasZnxM6mFlYAmBmyCuoiNAjlmiBVD37PjZHMlAgMBAAECggEBAKiHKOKisSDOZiIrgGOo3gAx3eSb6INhfLLuYbb+wTgyGOsoaRiz+vQdxMiaQYXSf6ms5fJVYE+mtuuw0wfv67GtEg993NXLQ/xNB2zZi//pqLLwk/dh4oXz9Y1shIr0iMgQS3VTgA/WoHAjvGi7gI+aHGNQA3kBjY2lkF1f04JFaV8n/ZXGyoredt8EuYMIwLf3tLAi5YF1i7eioR0fHU+VYnoLTMwgxkQ23QibATMMd3jIe6FUt6oYzJwOwm02NXlXCJxxjVXqCZfxuSRDNtAEoGf1DT0+yc7wEFzWrVoznw5CTUdTyPRouzKN29bgoJym0j7y5rSSwAlZZR3tyCECgYEA+AAt1qLI6TEws1QYGvzOJtwy3fgbkGFeLDrdm8lkurkEeKxvhjIUdQvnXui0NM8lDJvB6EQZ4Kf4fGNlqry+j9b2FLpdTta6FtZOd6VOYqrdQ4ShWcRPwNltU/eV2YScqJfAXyVsQ3OJE6/WmmEsNi1Z74+Y7l525PGlHQya/OkCgYEAucwRJGgY1zy/P84yooooPHc6xfF4ZhfJs7a2iKwxmfVjScWeeAvRNDUfoByqstkW2CpR8yV4SmFtiQ70XpjQTma67qUYPsmzdcFPbdnwrQVAor35o2q7gZRGpGXu4XySuGI8BlWc+teFnZfuNIbvcwZrEcrQXpqj/sVs9F4Mbt0CgYEAyuLinThZYyTh8aN3gQSW5oW4e41Rh4GQmGCkEaHl7TgVp19ycXeg8syFQUjgvF9GsRTvwsOL5BWmnKR4dQCqaWRztytr0GasoKg8U3eCNAgSsfzcP2Lx2BRIc6wWBHiP7QEQ2QX1lwz69Ici6vNaRww9ClYQx9myLMRfzu8UEJkCgYEAnI9QgpUVGYmevm1KTZyNeyYc6F8pTR4OYNk9xr0SruEP4UIc3ptWld+N3qVJUZuMnGpM085nJoYifrOTR4MNRINcUWvcmkvsZPWXsMFNBP7AEGJ00TdG+VGwlScvu+H04Fomqk/KD7U8aid0Gd76NrrZzgxQuOcl+bDytpfpciECgYBx3/8qN5/LQSbJ3AuBWGOaDulocjGIHzNVIKPWDiQp9PIzr6FAFCFo8VpI1KhFyBkxFcX+Ln8nEECOGLcVW4TxcK2NfWkJpdbmEu97Gqf7pes9VDVRrRQns3u7keeCsuMZvko8IDVHE7FyZnPXLmp65x/f1hgX0s5AoB0Pikd6Ng==


server:
  port: 9090
