fisco.crypto-material.certPath=conf/gm                       # The certification path
fisco.crypto-material.useSMCrypto=true

fisco.account.privateKey=-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQg42a5rdaHSWSjtE6k\nrBB6JBVBlTHCHLU2b/vhoSKwOl2gCgYIKoEcz1UBgi2hRANCAAQ3Utg4rx8w1YBk\ni0AkQKZxZaq7+snuQ92XPmZo+DPFreDJWTgsEDz1gkRuWv0k1/TiwWrle7jgJjFU\nD18+FiNF\n-----END PRIVATE KEY-----

fisco.network.defaultGroup=group1
fisco.network.peers[0]=192.168.50.183:20200
fisco.network.peers[1]=192.168.50.183:20201
fisco.network.peers[2]=192.168.50.183:20202
fisco.network.peers[3]=192.168.50.183:20203
fisco.account.keyStoreDir=account
fisco.account.accountFileFormat=pem
# ?????
fisco.thread-pool.threadPoolSize=16
# ??????
fisco.network.messageTimeout=100
fisco.webase.url= http://192.168.50.183:5002/WeBASE-Front
fisco.webase.groupId= 1

# cryptoMaterial.nableHsm=false
# cryptoMaterial.hsmLibPath=/usr/local/lib/libgmt0018.so
# cryptoMaterial.hsmKeyIndex=1
# cryptoMaterial.hsmPassword=12345678
# The following configurations take the certPath by default if commented
# cryptoMaterial.caCert=conf/ca.crt 
# cryptoMaterial.sslCert=conf/sdk.crt
# cryptoMaterial.sslKey=conf/sdk.key
# cryptoMaterial.enSslCert=conf/sm_ensdk.crt
# cryptoMaterial.enSslKey=conf/sm_ensdk.key
# The peer list to connect
# AMOP configuration
# Configure a private topic as a topic message sender.
# amop[0].publicKeys[0]=conf/amop/consumer_public_key_1.pem
# amop[0].topicName=PrivateTopic1
# Configure a private topic as a topic subscriber.
# amop[1].password=123456 
# amop[1].privateKey=conf/amop/consumer_private_key.p12
# amop[1].topicName=PrivateTopic2
# account.accountFilePath=conf
# account.accountAddress=0x
# account.password=123456
# threadPool.threadPoolSize=16
